apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: my-flask-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  selector:
    matchLabels:
      app: my-flask-app
  replicas: 5
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image:    395dac2f693b  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
